"""Add audit fields to customer and order history

Revision ID: 0699576f7cb5
Revises: 9475ff972d7d
Create Date: 2026-08-01 18:31:26.827942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0699576f7cb5'
down_revision = '9475ff972d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_history', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'action',
                sa.String(length=100),
                nullable=True
            )
        )
        batch_op.alter_column('field_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(
            "fk_customer_history_customer_id",
            "customers",
            ["customer_id"],
            ["id"]
        )

    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'action',
                sa.String(length=100),
                nullable=True
            )
        )
        batch_op.add_column(sa.Column('changed_by', sa.Integer(), nullable=True))
        batch_op.alter_column('field_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('changed_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.alter_column('changed_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('field_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('changed_by')
        batch_op.drop_column('action')

    with op.batch_alter_table('customer_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('field_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('action')

    # ### end Alembic commands ###
