"""Add account settings and legal foundation

Revision ID: 1b833e47eb29
Revises: 1407b4291493
Create Date: 2026-08-13 14:10:19.224006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b833e47eb29'
down_revision = '1407b4291493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'version', name='uq_legal_document_type_version')
    )
    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_documents_is_active'), ['is_active'], unique=False)

    op.create_table('user_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('legal_document_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('document_version', sa.String(length=30), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_consents_consent_type'), ['consent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_consents_legal_document_id'), ['legal_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_consents_user_id'), ['user_id'], unique=False)

    op.create_table('user_notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('order_notifications', sa.Boolean(), nullable=False),
    sa.Column('delivery_notifications', sa.Boolean(), nullable=False),
    sa.Column('security_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notification_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('user_privacy_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=False),
    sa.Column('personalization_enabled', sa.Boolean(), nullable=False),
    sa.Column('marketing_enabled', sa.Boolean(), nullable=False),
    sa.Column('data_sharing_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_privacy_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_privacy_preferences_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_privacy_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_privacy_preferences_user_id'))

    op.drop_table('user_privacy_preferences')
    with op.batch_alter_table('user_notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_preferences_user_id'))

    op.drop_table('user_notification_preferences')
    with op.batch_alter_table('user_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_consents_legal_document_id'))
        batch_op.drop_index(batch_op.f('ix_user_consents_consent_type'))

    op.drop_table('user_consents')
    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_documents_is_active'))
        batch_op.drop_index(batch_op.f('ix_legal_documents_document_type'))

    op.drop_table('legal_documents')
    # ### end Alembic commands ###
