"""add password reset fields to users

Revision ID: 64df9bc25d5a
Revises: 2f1eb208e8e9
Create Date: 2026-08-12 16:09:53.808923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64df9bc25d5a'
down_revision = '2f1eb208e8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['password_reset_token_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_reset_token_expires_at')
        batch_op.drop_column('password_reset_token_hash')

    # ### end Alembic commands ###
