"""Add order history table

Revision ID: 9475ff972d7d
Revises: a89074503e0a
Create Date: 2026-08-01 03:45:38.595947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9475ff972d7d'
down_revision = 'a89074503e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_history')
    # ### end Alembic commands ###
