"""add business name to users

Revision ID: 9fe4e5efefe2
Revises: c285f8ae73b7
Create Date: 2026-08-13 23:38:55.310410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe4e5efefe2'
down_revision = 'c285f8ae73b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_business_name'), ['business_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_business_name'))
        batch_op.drop_column('business_name')

    # ### end Alembic commands ###
