"""Add measurement_type to measurements

Revision ID: a09194da1200
Revises: f7bf30a11dad
Create Date: 2026-08-06 12:56:36.673325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09194da1200'
down_revision = 'f7bf30a11dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table(
        "measurements",
        schema=None
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                "measurement_type",
                sa.String(length=50),
                nullable=False,
                server_default="Initial"
            )
        )

    op.execute(
        """
        UPDATE measurements
        SET measurement_type = 'Initial'
        WHERE measurement_type IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_column('measurement_type')

    # ### end Alembic commands ###
