"""Create marketplace listings table

Revision ID: c285f8ae73b7
Revises: 167c1d28b49e
Create Date: 2026-08-13 17:21:43.525692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c285f8ae73b7'
down_revision = '167c1d28b49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_listings_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listings_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listings_style_id'), ['style_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_style_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_featured'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_category'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_business_id'))

    op.drop_table('marketplace_listings')
    # ### end Alembic commands ###
