"""Create styles table

Revision ID: c319893691c9
Revises: e674646a74f3
Create Date: 2026-08-07 16:05:44.730538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c319893691c9'
down_revision = 'e674646a74f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garment_type', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('estimated_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fabric_requirement', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reference_source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('reference_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('collection', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('designer', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('season', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('occasion', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('price_estimate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('primary_colour', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('secondary_colour', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('styles_style_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_styles_style_code'), ['style_code'], unique=True)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_styles_style_code'))
        batch_op.create_unique_constraint(batch_op.f('styles_style_code_key'), ['style_code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('secondary_colour')
        batch_op.drop_column('primary_colour')
        batch_op.drop_column('price_estimate')
        batch_op.drop_column('occasion')
        batch_op.drop_column('season')
        batch_op.drop_column('designer')
        batch_op.drop_column('collection')
        batch_op.drop_column('status')
        batch_op.drop_column('reference_url')
        batch_op.drop_column('reference_source')
        batch_op.drop_column('tags')
        batch_op.drop_column('fabric_requirement')
        batch_op.drop_column('estimated_days')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('garment_type')

    # ### end Alembic commands ###
