"""Add style relationship to orders

Revision ID: ea2c14b03637
Revises: c319893691c9
Create Date: 2026-08-08 05:18:20.297035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2c14b03637'
down_revision = 'c319893691c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'styles', ['style_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('style_id')

    # ### end Alembic commands ###
