"""Add listing reference to conversations

Revision ID: f30d39ebbead
Revises: 9fe4e5efefe2
Create Date: 2026-08-14 02:18:48.791954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30d39ebbead'
down_revision = '9fe4e5efefe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_listing_id'), ['listing_id'], unique=False)
        batch_op.create_foreign_key(None, 'marketplace_listings', ['listing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_listing_id'))
        batch_op.drop_column('listing_id')

    # ### end Alembic commands ###
